// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcy-MbN6eTBqHp4_8pWA5Tz9qIZLKaLyo',
    appId: '1:746018546285:web:e03799e059cfe58e5e9564',
    messagingSenderId: '746018546285',
    projectId: 'body-evolution-gym',
    authDomain: 'body-evolution-gym.firebaseapp.com',
    storageBucket: 'body-evolution-gym.appspot.com',
    measurementId: 'G-LLT1JHF8SS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqCLLFWd57C5_hwTi8XQaVzzJcYmkggg8',
    appId: '1:746018546285:android:3acbaaf8564469ab5e9564',
    messagingSenderId: '746018546285',
    projectId: 'body-evolution-gym',
    storageBucket: 'body-evolution-gym.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzH6sPCz8FUHPtIZR7fx9KLWrmdVYpniw',
    appId: '1:746018546285:ios:c4d8f8210d83838f5e9564',
    messagingSenderId: '746018546285',
    projectId: 'body-evolution-gym',
    storageBucket: 'body-evolution-gym.appspot.com',
    iosBundleId: 'com.example.flutterjs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzH6sPCz8FUHPtIZR7fx9KLWrmdVYpniw',
    appId: '1:746018546285:ios:e3fe9de6d1978d125e9564',
    messagingSenderId: '746018546285',
    projectId: 'body-evolution-gym',
    storageBucket: 'body-evolution-gym.appspot.com',
    iosBundleId: 'com.example.flutterjs.RunnerTests',
  );
}
